method_name: "frame_infer"

infer_dataset_top_directory: "/home/ssd_dir/rgbd_airsim_image/mono_depth_images_2/inference_image/Building99/inference1000"
csv_name: "data_list.csv"

weights_top_directory: "/home/ssd_dir/mono_and_depth_image_attitude_estimator_log/ozaki/regression_train_2022_03_02/"
weights_file_name: "weights.pth"

infer_log_top_directory: "/home/ssd_dir/mono_and_depth_image_attitude_estimator_log/regression_train_2022_03_02/infer_log/"
infer_log_file_name: "frame_infer_relust_Building99.csv"

resize: 224
mean_element: 0.5
std_element: 0.5
dim_fc_out: 3
dropout_rate: 0.1
num_sampling: 15
original_size: 672