method_name: "regression"

save_top_path: "/home/log/mle_train_2022_03_04/"

train:
  - "/home/strage/rgbd_airsim_image/mono_depth_images_2/image50000"
  - "/home/strage/rgbd_airsim_image/mono_depth_images_2/image50000_2"
  - "/home/strage/rgbd_airsim_image/mono_depth_images_2/image50000_3"
valid:
   - "/home/strage/rgbd_airsim_image/mono_depth_images_2/image25000"


multiGPU: 1 #1 is ture

hyperparameter:
  original_size: 672
  resize: 224
  mean_element: 0.5
  std_element: 0.5
  hor_fov_deg: 70
  optimizer_name: "Adam"
  lr_cnn: 1e-5
  lr_fc: 1e-5
  batch_size: 256
  num_epochs: 50
  dropout_rate: 0.1
  weight_decay: 0.01
  dim_fc_out: 9