method_name: "regression"

save_top_path: "/home/log/regression_train_2022_03_03"
weights_path: "/weights"
log_path: "/log"
graph_path: "/graph"

train:
  - "/home/strage/rgbd_airsim_image/mono_depth_images_2/image50000"
  - "/home/strage/rgbd_airsim_image/mono_depth_images_2/image50000_2"
  - "/home/strage/rgbd_airsim_image/mono_depth_images_2/image50000_3"
valid:
   - "/home/strage/rgbd_airsim_image/mono_depth_images_2/image25000"

csv_name: "data_list.csv"

multiGPU: 1 #1 is multiGPU

hyperparameter:
  original_size: 672
  resize: 224
  mean_element: 0.5
  std_element: 0.5
  hor_fov_deg: 70
  optimizer_name: "Adam"
  lr_cnn: 1e-4
  lr_roll_fc: 1e-4
  lr_pitch_fc: 1e-4
  lr_fc: 1e-4
  weight_decay: 0.0001
  batch_size: 256
  num_epochs: 50
  dropout_rate: 0.1
  dim_fc_out: 3