save_top_path: "/home/log/mono_train_2022_02_22"
weights_path: "/weights"
log_path: "/log"
graph_path: "/graph"

train:
  - "/home/strage/rgbd_airsim_image/mono_depth_images_2/image50000"
  - "/home/strage/rgbd_airsim_image/mono_depth_images_2/image50000_2"
  - "/home/strage/rgbd_airsim_image/mono_depth_images_2/image50000_3"
valid:
   - "/home/strage/rgbd_airsim_image/mono_depth_images_2/image25000"

csv_name: "data_list.csv"

index_csv_path: "/home/pycode/mono_and_depth_image_attitude_estimator/index_dict/index_dict_-30_30_range_step1deg.csv"

pretrained_model: "/home/pycode/mono_and_depth_image_attitude_estimator/weights/resnet101-63fe2227.pth"
##pretrained_model: "/home/pycode/mono_and_depth_image_attitude_estimator/weights/resnet101_v1c.pth"

multiGPU: 1 #1 is ture

hyperparameter:
  original_size: 672
  resize: 224
  mean_element: 0.5
  std_element: 0.5
  dim_fc_out: 61
  batch_size: 256
  num_epochs: 50
  optimizer_name: "Adam"
  lr_resnet: 1e-4
  lr_roll_fc: 1e-4
  lr_pitch_fc: 1e-4
  weight_decay: 0.00
  alpha: 5e-5