method_name: "frame_infer"

infer_dataset_top_directory: "/home/ssd_dir/airsim_dataset_kawai/AirSimNH/infer_image_range_30_30/dir1_infer_image1000/"
csv_name: "image_attitude.csv"

weights_top_directory: "/home/ssd_dir/cnn_attitude_estimator_log/range_30/dgx_test1/"
weights_file_name: "weights.pth"

infer_log_top_directory: "/home/ssd_dir/cnn_attitude_estimator_log/infer_log/range_30/2021_08_09_mc_dropout/"
infer_log_file_name: "frame_infer_relust.csv"

index_dict_name: "index_dict_-30_30_range_step1deg.csv"

window_original_size: 480
original_size: 480
window_num: 15
resize: 224
mean_element: 0.5
std_element: 0.5
dim_fc_out: 61
enable_dropout: False
dropout_rate: 0.1
corner_threshold: 30
