method_name: "frame_infer"

infer_dataset_top_directory: "/home/ssd_dir/rgbd_airsim_image/color_depth_images/inference_image/AirSimNH/image1000"
#infer_dataset_top_directory: "/home/ssd_dir/rgbd_airsim_image/color_depth_images/inference_image/Building99/test100"
csv_name: "data_list.csv"

weights_top_directory: "/home/ssd_dir/mono_and_depth_image_attitude_estimator_log/classification_train_2022_02_17"
weights_file_name: "weights.pth"

infer_log_top_directory: "/home/ssd_dir/mono_and_depth_image_attitude_estimator_log/classification_train_2022_02_17/infer_log"
infer_log_file_name: "frame_infer_relust.csv"

index_dict_name: "index_dict_-30_30_range_step1deg.csv"

window_original_size: 480
original_size: 480
window_num: 10
resize: 224
mean_element: 0.5
std_element: 0.5
dim_fc_out: 61
enable_dropout: False
dropout_rate: 0.1
corner_threshold: 30
