method_name: "regression"

save_top_path: "/home/log/classification_train_2022_02_11_3"
weights_path: "/weights"
log_path: "/log"
graph_path: "/graph"

train:
  - "/home/ssd_dir/rgbd_airsim_image/color_depth_images/image50000"
valid:
   - "/home/ssd_dir/rgbd_airsim_image/color_depth_images/test100"

csv_name: "data_list.csv"

index_csv_path: "/home/pycode/mono_and_depth_image_attitude_estimator/index_dict/index_dict_-30_30_range_step1deg.csv"

multiGPU: 0 #1 is ture

hyperparameter:
  original_size: 480
  resize: 224
  mean_element: 0.5
  std_element: 0.5
  hor_fov_deg: 70
  optimizer_name: "AdamW" #SGD or Adam or AdamW
  loss_function: "CrossEntropyLoss" #CrossEntropyLoss or MSELoss .
  lr_cnn: 1e-4
  lr_roll_fc: 1e-4
  lr_pitch_fc: 1e-4
  weight_decay: 0.0
  batch_size: 16
  num_epochs: 50
  dropout_rate: 0.1
  dim_fc_out: 61
  alpha: 3e-6
  clip_limit: 0.1